package com.mathgeniusguide.project8.util

import com.mathgeniusguide.project8.R
import android.content.res.Resources


class TestResources : Resources(null, null, null) {
    override fun getString(id: Int): String {
        try {
            return when (id) {
                R.string.app_name -> "Go4Lunch"
                R.string.logout -> "Logout"
                R.string.settings -> "Settings"
                R.string.instructions -> "Instructions"
                R.string.your_lunch -> "Your Lunch"
                R.string.list_view -> "List View"
                R.string.login -> "login"
                R.string.map_view -> "Map View"
                R.string.restaurant_page -> "Restaurant Page"
                R.string.restaurant_website -> "Restaurant Website"
                R.string.search -> "Search"
                R.string.workmates -> "Workmates"
                R.string.chat -> "Chat"
                R.string.navigation_drawer_open -> "Drawer Open"
                R.string.navigation_drawer_close -> "Drawer Close"
                R.string.you_are_here -> "You Are Here"
                R.string.loading_nearby_places -> "Loading Nearby Places"
                R.string.loading_info_for -> "Loading Info For %1\$s"
                R.string.closing_soon -> "Closing Soon"
                R.string.open_until -> "Open Until %1\$s"
                R.string.open_24 -> "Open For Next 24 Hours"
                R.string.open_24_7 -> "Open 24/7"
                R.string.opens_at -> "Opens At %1\$s"
                R.string.opens_tomorrow_at -> "Opens Tomorrow At %1\$s"
                R.string.opens_day_at -> "Opens %1\$s At %2\$s"
                R.string.workmates_placeholder -> "This workmate hasn't decided yet."
                R.string.hasnt_decided_yet -> "%1\$s hasn't decided yet."
                R.string.is_eating_at -> "%1\$s is eating at %2\$s."
                R.string.call -> "CALL"
                R.string.like -> "LIKE"
                R.string.website -> "WEBSITE"
                R.string.is_joining -> "%1\$s is joining!"
                R.string.restaurant_workmates_rv_placeholder -> "No workmates are eating here yet."
                R.string.sunday -> "Sunday"
                R.string.monday -> "Monday"
                R.string.tuesday -> "Tuesday"
                R.string.wednesday -> "Wednesday"
                R.string.thursday -> "Thursday"
                R.string.friday -> "Friday"
                R.string.saturday -> "Saturday"
                R.string.date_at_time -> "%1\$s at %2\$s"
                R.string.no_lunch_chosen -> "You have not yet chosen a place to eat."
                R.string.load_chosen_failed -> "Failed to load list of chosen restaurants."
                R.string.load_nearby_failed -> "Failed to load list of nearby restaurants."
                R.string.no_website -> "This restaurant does not have a website."
                R.string.no_phone -> "This restaurant does not have a phone number."
                R.string.search_radius -> "Search Radius (meters)"
                R.string.listview_order -> "List View Sort Order"
                R.string.shortest_distance -> "shortest distance"
                R.string.highest_rating -> "highest rating"
                R.string.most_workmates -> "most workmates"
                R.string.alphabetical -> "alphabetical by name"
                R.string.notification_time -> "Notification Time"
                R.string.facebook_app_id -> "2174751236152917"
                R.string.fb_login_protocol_scheme -> "fb2174751236152917"
                R.string.notification_title -> "You have chosen to eat at %1\$s."
                R.string.eating_alone -> "You will be eating alone."
                R.string.one_person_joining -> "%1\$s is joining you."
                R.string.multiple_people_joining -> "%1\$s and %2\$s are joining you."
                R.string.save -> "SAVE"
                R.string.login_screen -> "Login Screen"
                R.string.login_screen_1 -> "If you are not logged in, only the Login screen will be visible. You have the option of logging in with a Google or Facebook account."
                R.string.map_screen -> "Map Screen"
                R.string.map_screen_1 -> "Immediately after logging in, or immediately after opening the app if you are already logged in, the Map screen will be visible."
                R.string.map_screen_2 -> "The map screen will be centered on your location. Nearby restaurants will be shown with markers at the restaurant's location."
                R.string.map_screen_3 -> "Immediately after opening the app, it may take some time to load the nearby restaurants."
                R.string.map_screen_4 -> "Clicking on a marker for a restaurant will display the restaurant's name. Clicking on the restaurant's name will display the page for that restaurant."
                R.string.list_screen -> "List Screen"
                R.string.list_screen_1 -> "Instead of displaying the nearby restaurants in a map, you also have the option to display them as a list."
                R.string.list_screen_2 -> "The list will show details about the restaurant including the distance from you, the address, the opening or closing time, the rating (0 to 3 stars), and the number of workmates who are joining you."
                R.string.list_screen_3 -> "Depending on your settings, the restaurants can be sorted by shortest distance first, by highest rating first, by most workmates joining first, or alphabetical by name. Restaurants that you like will always be shown first."
                R.string.list_screen_4 -> "Clicking a restaurant will display the page for that restaurant."
                R.string.workmates_screen -> "Workmates Screen"
                R.string.workmates_screen_1 -> "The Workmates screen shows a list of all of your workmates."
                R.string.workmates_screen_2 -> "Each workmate will show their photo, their name, and the restaurant that they chose to eat at."
                R.string.workmates_screen_3 -> "Clicking a workmate will display a page for you to chat with that workmate."
                R.string.restaurant_screen -> "Restaurant Screen"
                R.string.restaurant_screen_1 -> "The Restaurant screen is displayed whenever you click a restaurant in the Map screen or List screen."
                R.string.restaurant_screen_2 -> "The restaurant's name, rating, address, and photo will be displayed."
                R.string.restaurant_screen_3 -> "Clicking the checkbox will select this restaurant as where you will be eating for lunch."
                R.string.restaurant_screen_4 -> "Clicking \"Call\" will open a dialer with the restaurant's phone number entered."
                R.string.restaurant_screen_5 -> "Clicking \"Like\" will cause this restaurant to be displayed before other restaurants in the List screen."
                R.string.restaurant_screen_6 -> "Clicking \"Website\" will display the webpage for this restaurant."
                R.string.restaurant_screen_7 -> "If workmates are joining you, they will be displayed. Clicking a workmate will display a page for you to chat with that workmate."
                R.string.chat_screen -> "Chat Screen"
                R.string.chat_screen_1 -> "Clicking a workmate in the Workmates screen or the Restaurant screen will display a Chat screen, where you can chat with that workmate."
                R.string.chat_screen_2 -> "Messages between you and your workmate will be displayed, along with the sender's photo and the time that the message was sent."
                R.string.search_1 -> "Clicking the search icon will display a search field."
                R.string.search_2 -> "When you begin typing, suggestions of nearby restaurants will be shown."
                R.string.search_3 -> "Clicking a restaurant will display the page for that restaurant."
                R.string.search_4 -> "If the restaurant is not already in the Map screen and List screen, it will be added."
                R.string.menu -> "Menu"
                R.string.menu_1 -> "Clicking the drawer icon or swiping from left to right will display a menu."
                R.string.menu_2 -> "Clicking \"Your Lunch\" will display the page for your chosen restaurant."
                R.string.menu_3 -> "Clicking \"Settings\" will display the Settings screen, where you can change your settings."
                R.string.menu_4 -> "Clicking \"Log Out\" will log you out and display the Login screen"
                R.string.settings_screen -> "Settings Screen"
                R.string.settings_screen_1 -> "The \"Search Radius\" field allows you to change the maximum distance for nearby restaurants. This setting will take effect the next time you open the app."
                R.string.settings_screen_2 -> "The \"List View Sort Order\" field allows you to change the order that the restaurants are displayed in the List screen."
                R.string.settings_screen_3 -> "The \"Notification Time\" field allows you to change the time of day that you'll receive a notification telling you where you chose to eat and who is joining you."
                R.string.settings_screen_4 -> "The \"Save\" button saves your settings."
                else -> ""
            }
        } catch (e: NotFoundException) {
            return ""
        }
    }

}